# -*- coding: utf-8 -*-
"""k-means cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o3Ovw7yNrHowyO55wrlmhFZYap6VyIzs
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
# %matplotlib inline

df=pd.read_csv('Mall_customers.csv')
df.head()

model=KMeans(n_clusters=3, init='k-means++',random_state=42)
y_Kmeans=model.fit_predict(df.iloc[:,[3,4]].values)

x=df.iloc[:,[3,4]].values
plt.scatter(x[y_Kmeans==0,0],x[y_Kmeans==0,1],s=100, c='red',label='cluster 1')
plt.scatter(x[y_Kmeans==1,0],x[y_Kmeans==1,1],s=100, c='blue',label='cluster 2')
plt.scatter(x[y_Kmeans==2,0],x[y_Kmeans==2,1],s=100, c='green',label='cluster 3')
plt.scatter(model.cluster_centers_[:,0],model.cluster_centers_[:,1],s=300,c='yellow',label='Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

wcss=[]
for u in range(1,11):
  model=KMeans(n_clusters=u,init='k-means++',random_state=42)
  model.fit(x)
  wcss.append(model.inertia_)

plt.plot(range(1,11),wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('wcss')
plt.show()

model=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_kmeans=model.fit_predict(x)

plt.scatter(x[y_kmeans==0,0],x[y_kmeans==0,1],s=100, c='red', label='Cluster 1')
plt.scatter(x[y_kmeans==1,0],x[y_kmeans==1,1],s=100, c='blue', label='Cluster 2')
plt.scatter(x[y_kmeans==2,0],x[y_kmeans==2,1],s=100, c='green', label='Cluster 3')
plt.scatter(x[y_kmeans==3,0],x[y_kmeans==3,1],s=100, c='cyan', label='Cluster 4')
plt.scatter(x[y_kmeans==4,0],x[y_kmeans==4,1],s=100, c='magenta', label='Cluster 5')
plt.scatter(model.cluster_centers_[:,0],model.cluster_centers_[:,1],s=300,c='yellow',label='Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

